[arguments]
dst_host = "127.0.0.1"
dst_port = 8888
in_width = 640
in_height = 480
out_width = 640
out_height = 480
gop = 30
process_log_level = "quiet"
ffmpeg_proc_path = "ffmpeg_launcher_vp8.sh.template" 

[meta]
